### ISSUE TITLE
Return response headers in each API

### ISSUE THREAD

**Issue by rockuw** [aliyun/fc-nodejs-sdk#12]
我们有一些自定义的header返回，例如`x-fc-error-type`, `x-fc-request-id`, `x-fc-log-result`等。

当前接口返回的是response body，能否直接将response返回？

这样改动会有兼容性问题吗？ @JacksonTian

**Comment by JacksonTian** [comment]
是在正常调用的情况下返回这些 headers 吗，还是只在异常的情况下才返回？

**Comment by rockuw** [comment]
1. `x-fc-request-id`是在任何API，任何情况下都会返回的
2. `x-fc-error-type`, `x-fc-log-result`只在invokeFunction的时候会返回，不是异常情况

**Comment by AntSworD** [comment]
@rockuw 调用如果返回 request-id的话，也方便开发者去日志 debug

**Comment by JacksonTian** [comment]
如果需求强烈的话，我们需要发一个大版本。返回 x-fc-* 相关的 headers

**Comment by AntSworD** [comment]
我现在是自己改了下源代码提取 requestid ，现在用处也不大，日志里并没有 requestid 的维度

**Comment by rockuw** [comment]
@AntSworD 请使用@alicloud/fc2，支持返回headers了
