### ISSUE TITLE
这个是将错就错了吗？

### ISSUE THREAD

**Issue by jinchun** [aliyun/fc-nodejs-sdk#27]
https://github.com/aliyun/fc-nodejs-sdk/blob/e33d80091526818c92871d9b61af98669ae3eee9/lib/client.js#L113-L116

JavaScript 里 `{}` 直接用来判断，为`true`，所以这里的结果永远会在变量`str`后面加上一个可能没有意义的`\n`（也许是有意义的，但我用其他语言写这个签名算法时，参考本代码被误导，始终缺少一个`\n`，后来追这份代码，加上`\n`后，签名验证通过）。
https://github.com/aliyun/fc-nodejs-sdk/blob/e33d80091526818c92871d9b61af98669ae3eee9/lib/helper.js#L39-L58

如果有意义，是否可以将代码稍作修改，将 line 57的第一个`\n`移动到 line 39的末尾？

**Comment by rocaltair** [comment]
@jinchun 您好~
先说声抱歉，这个地方确实算是将错就错而实现的。
最初的版本queries没有参与签名，如果要更新sdk，相关的ListService等API会收到影响，所以这里只更改了HTTP Trigger invoke相关的签名。
因为直接修改会导致现有旧的客户端不可用，很长一段时间里这里只能将错就错了。
