### ISSUE TITLE
创建服务Client.createService时 传入参数 vpcConfig 报错400 - Argument 'vpcConfig' is not supported

### ISSUE THREAD

**Issue by microfly2008** [aliyun/fc-nodejs-sdk#28]
创建service时 传入参数 vpcConfig 报错400 - Argument 'vpcConfig' is not supported。
我已经根据 阿里云官网文档来做的
[API文档](https://help.aliyun.com/document_detail/52877.html?spm=a2c4g.11186623.6.605.bWUtwY#vpcconfig)
[FC文档](https://help.aliyun.com/knowledge_detail/72959.html?spm=a2c4g.11186623.6.562.k05AYm#h2-u4F7Fu7528u793Au4F8B4)

### 代码：
`vpcConfig = {
  'securityGroupId':'sg-1111',
  'vSwitchIds':['vsw-1111'],
  'vpcId':'vpc-1111
}`
`service = await fc.createService(serviceName, {
      description: serviceDescription,
      vpcConfig: vpcConfig
    });`

### 报错
` {"ErrorCode":"InvalidArgument","ErrorMessage":"Argument 'vpcConfig' is not supported"}`

### SDK debug跟踪

/2016-08-15/services +4ms
  lambda request headers: {"accept":"application/json","date":"Fri, 15 Jun 2018 03:22:03 GMT","host":"111111111.cn-shenzhen.fc.aliyuncs.com","user-agent":"Node.js(v9.10.1) OS(darwin/x64) SDK(@alicloud/fc2@v2.0.3)","x-fc-account-id":"222222","content-type":"application/json","content-length":59,"content-md5":"11111111111=","authorization":"FC LTAIldIgp2DLHiGG="} +1ms
  httpx > POST /2016-08-15/services HTTP/1.1 +14ms
  httpx > accept: application/json +0ms
  httpx > date: Fri, 15 Jun 2018 03:22:03 GMT +1ms
  httpx > host: 111111.cn-shenzhen.fc.aliyuncs.com +0ms
  httpx > user-agent: Node.js(v9.10.1) OS(darwin/x64) SDK(@alicloud/fc2@v2.0.3) +0ms
  httpx > x-fc-account-id: 111111111 +0ms
  httpx > content-type: application/json +0ms
  httpx > content-length: 59 +0ms
  httpx > content-md5: MDJhZWRkM2M= +0ms
  httpx > authorization: FC LTAIldI5dNkEtEi/RZw= +0ms
  httpx > Connection: keep-alive +0ms
  httpx >  +0ms
  httpx >  +0ms
  httpx < HTTP/1.1 400 Bad Request +0ms
  httpx < access-control-allow-origin:  +0ms
  httpx < access-control-expose-headers: Date,x-fc-request-id,x-fc-error-type,x-fc-code-checksum,x-fc-max-memory-usage,x-fc-log-result,x-fc-invocation-code-version +1ms
  httpx < content-type: application/json; charset=utf-8 +0ms
  httpx < x-fc-error-type: FCCommonError +0ms
  httpx < x-fc-request-id: 96-a60afc60d7b +0ms
  httpx < date: Fri, 15 Jun 2018 03:22:03 GMT +0ms
  httpx < content-length: 86 +0ms
  lambda response status: 400 +0ms
  lambda response headers: {"access-control-allow-origin":"","access-control-expose-headers":"Date,x-fc-request-id,x-fc-error-type,x-fc-code-checksum,x-fc-max-memory-usage,x-fc-log-result,x-fc-invocation-code-version","content-type":"application/json; charset=utf-8","x-fc-error-type":"FCCommonError","x-fc-request-id":"962b1-7afc60d7b","date":"Fri, 15 Jun 2018 03:22:03 GMT","content-length":"86"} +1ms
  httpx  +0ms
  httpx {"ErrorCode":"InvalidArgument","ErrorMessage":"Argument 'vpcConfig' is not supported"} +0ms

### **lambda response body: {"ErrorCode":"InvalidArgument","ErrorMessage":"Argument 'vpcConfig' is not supported"} +0ms**

FCInvalidArgumentError: POST /services failed with 400. requestid: 9625-7080, message: Argument 'vpcConfig' is not supported.
    at Client.request (/Applications/mampstack-5.5.30-0/apache2/htdocs/ali-func/fcvpc/node_modules/.2.0.3@@alicloud/fc2/lib/client.js:148:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

**Comment by CiCi503** [comment]
您好，
    VPC 功能目前在香港集群、新加坡集群、悉尼集群开放，供您试用。深圳集群暂不支持 VPC 功能，所以会报错。预计 6 月底会将 VPC 功能发布到所有集群。
温馨提示：为服务配置访问 VPC 的功能时，需要为服务配置角色，该角色有对 ENI 的创建、描述、删除等权限，您在创建服务时要指定这个角色。

例如：
client.createService(serviceName, { description: "serviceDescription", role: "acs:ram::11111:role/roleName", vpcConfig: vpcConfig }).then()

    您可以加入函数计算的官网用户群，钉钉群号：11721331，可以在群里获得函数计算的最新消息，您也可以在群里咨询问题，函数计算的工程师会第一时间回复。

感谢您使用阿里云函数计算！
------------------------------------------------------------------
发件人：microfly2008 <notifications@github.com>
发送时间：2018年6月15日(星期五) 11:36
收件人：aliyun/fc-nodejs-sdk <fc-nodejs-sdk@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[aliyun/fc-nodejs-sdk] 创建服务Client.createService时 传入参数 vpcConfig 报错400 - Argument 'vpcConfig' is not supported (#28)

创建service时 传入参数 vpcConfig 报错400 - Argument 'vpcConfig' is not supported。
 我已经根据 阿里云官网文档来做的
API文档
FC文档代码：
vpcConfig = { 'securityGroupId':'sg-1111', 'vSwitchIds':['vsw-1111'], 'vpcId':'vpc-1111 }
service = await fc.createService(serviceName, { description: serviceDescription, vpcConfig: vpcConfig });报错
{"ErrorCode":"InvalidArgument","ErrorMessage":"Argument 'vpcConfig' is not supported"}SDK debug跟踪
/2016-08-15/services +4ms
 lambda request headers: {"accept":"application/json","date":"Fri, 15 Jun 2018 03:22:03 GMT","host":"111111111.cn-shenzhen.fc.aliyuncs.com","user-agent":"Node.js(v9.10.1) OS(darwin/x64) SDK(@v2.0.3)","x-fc-account-id":"222222","content-type":"application/json","content-length":59,"content-md5":"11111111111=","authorization":"FC LTAIldIgp2DLHiGG="} +1ms
 httpx > POST /2016-08-15/services HTTP/1.1 +14ms
 httpx > accept: application/json +0ms
 httpx > date: Fri, 15 Jun 2018 03:22:03 GMT +1ms
 httpx > host: 111111.cn-shenzhen.fc.aliyuncs.com +0ms
 httpx > user-agent: Node.js(v9.10.1) OS(darwin/x64) SDK(@v2.0.3) +0ms
 httpx > x-fc-account-id: 111111111 +0ms
 httpx > content-type: application/json +0ms
 httpx > content-length: 59 +0ms
 httpx > content-md5: MDJhZWRkM2M= +0ms
 httpx > authorization: FC LTAIldI5dNkEtEi/RZw= +0ms
 httpx > Connection: keep-alive +0ms
 httpx > +0ms
 httpx > +0ms
 httpx < HTTP/1.1 400 Bad Request +0ms
 httpx < access-control-allow-origin: +0ms
 httpx < access-control-expose-headers: Date,x-fc-request-id,x-fc-error-type,x-fc-code-checksum,x-fc-max-memory-usage,x-fc-log-result,x-fc-invocation-code-version +1ms
 httpx < content-type: application/json; charset=utf-8 +0ms
 httpx < x-fc-error-type: FCCommonError +0ms
 httpx < x-fc-request-id: 96-a60afc60d7b +0ms
 httpx < date: Fri, 15 Jun 2018 03:22:03 GMT +0ms
 httpx < content-length: 86 +0ms
 lambda response status: 400 +0ms
 lambda response headers: {"access-control-allow-origin":"","access-control-expose-headers":"Date,x-fc-request-id,x-fc-error-type,x-fc-code-checksum,x-fc-max-memory-usage,x-fc-log-result,x-fc-invocation-code-version","content-type":"application/json; charset=utf-8","x-fc-error-type":"FCCommonError","x-fc-request-id":"962b1-7afc60d7b","date":"Fri, 15 Jun 2018 03:22:03 GMT","content-length":"86"} +1ms
 httpx +0ms
 httpx {"ErrorCode":"InvalidArgument","ErrorMessage":"Argument 'vpcConfig' is not supported"} +0mslambda response body: {"ErrorCode":"InvalidArgument","ErrorMessage":"Argument 'vpcConfig' is not supported"} +0ms
FCInvalidArgumentError: POST /services failed with 400. requestid: 9625-7080, message: Argument 'vpcConfig' is not supported.
 at Client.request (/Applications/mampstack-5.5.30-0/apache2/htdocs/ali-func/fcvpc/node_modules/.2.0.3@/lib/client.js:148:19)
 at 
 at process._tickCallback (internal/process/next_tick.js:118:7)

**Comment by microfly2008** [comment]
回复非常快，谢谢！
