### ISSUE TITLE
Invoke error from frontend: required HTTP header Date was not specified

### ISSUE THREAD

**Issue by Lellansin** [aliyun/fc-nodejs-sdk#43]
When I use this SDK to invoke my FC function, I got a 400 error, while do the POST request. it is said:

```json
{"ErrorCode":"MissingRequiredHeader","ErrorMessage":"required HTTP header Date was not specified"}
```

And I checked the http.request method which automatically bundled by tool like parcel. Then I found, it's forbidden for frontend to do http request with `date` header (check [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date) for more).

Is there any suggestion to me for invoking the FC function from frontend?

**Comment by muxiangqiu** [comment]
可以使用 x-fc-date 来代替前端的 request date，x-fc-date 放到 header 里面

**Comment by Lellansin** [comment]
Thanks, use `x-fc-date` header works for me.
